### ISSUE TITLE
不能注册

### ISSUE THREAD

**Issue by jingbeibei** [boredream/DesignResCollectionApp#1]
提示不允许客户端注册

**Comment by boredream** [comment]
你是自己申请leancloud的key还是用我项目里的key

**Comment by jingbeibei** [comment]
你项目里的 @boredream

**Comment by boredream** [comment]
我看了下现在leancloud发送短信加了签名审核什么的，你还是先用https://github.com/boredream/DesignResCollection/tree/master/DesignResCollection_MVP 这个项目看一下吧，那边我设置成直接注册不需要发短信验证的

**Comment by jingbeibei** [comment]
好的，O(∩_∩)O谢谢
